# Generated by Django 2.2.19 on 2021-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsearch', '0002_auto_20210515_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuedetail',
            name='land_type',
            field=models.CharField(choices=[('a', 'തെങ്ങ് പ്രധാന വിളയായ ഭൂമി'), ('b', 'കവുങ്ങ് പ്രധാന വിളയായ ഭൂമി'), ('c', 'കുരുമുളക് പ്രധാന വിളയായ ഭൂമി'), ('d', 'കശുമാവ് പ്രധാന വിളയായ ഭൂമി'), ('e', 'മറ്റ് കര ഭൂമി'), ('f', 'പള്ളിയാൽ ഭൂമി')], help_text='Select the type of land.', max_length=1),
        ),
    ]
