# Generated by Django 2.2.19 on 2021-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(max_length=1)),
                ('card_no', models.CharField(max_length=20)),
                ('mem_name', models.CharField(max_length=200)),
                ('land', models.FloatField(max_length=200)),
                ('district', models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukk'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malappuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Thiruvananthapuram'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], help_text='Select the district', max_length=2)),
                ('land_type', models.CharField(choices=[('a', 'തെങ്ങ് പ്രധാന വിളയായ ഭൂമി'), ('b', 'കവുങ്ങ് പ്രധാന വിളയായ ഭൂമി'), ('c', 'കുരുമുളക് പ്രധാന വിളയായ ഭൂമി'), ('d', 'കശുമാവ് പ്രധാന വിളയായ ഭൂമി'), ('e', 'മറ്റ് കര ഭൂമി'), ('f', 'പള്ളിയാൽ ഭൂമി')], help_text='Select the type of land.', max_length=1)),
                ('email_id', models.CharField(max_length=200)),
            ],
        ),
    ]
